name: Build SDL2 Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SDL2 dependencies
        run: |
          sudo apt update
          sudo apt install -y libsdl2-dev

      - name: Rename sdl2.pc to SDL2.pc
        run: |
          sudo mv /usr/lib/x86_64-linux-gnu/pkgconfig/sdl2.pc /usr/lib/x86_64-linux-gnu/pkgconfig/SDL2.pc

      - name: Set PKG_CONFIG_PATH
        run: |
          echo "export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Build project with Make
        run: |
          make build

      - name: Clean up
        run: |
          make clean
